In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/world-happiness/2015.csv
/kaggle/input/world-happiness/2017.csv
/kaggle/input/world-happiness/2019.csv
/kaggle/input/world-happiness/2018.csv
/kaggle/input/world-happiness/2016.csv

**Import packages**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Load data set**
Pandas is used to read the datasets.

In [3]:
df2015 = pd.read_csv("/kaggle/input/world-happiness/2015.csv")

In [4]:
df2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [5]:
df2016 = pd.read_csv("/kaggle/input/world-happiness/2016.csv")
df2017 = pd.read_csv("/kaggle/input/world-happiness/2017.csv")
df2018 = pd.read_csv("/kaggle/input/world-happiness/2018.csv")
df2019 = pd.read_csv("/kaggle/input/world-happiness/2019.csv")

In [6]:
df2016.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [7]:
df2017.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [8]:
df2018.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357

In [9]:
df2019.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

**Data exploration******(EDA and data cleaning)****
* Understand the variables
* Clean the dataset (missing data, redundant data, renaming columns, dropping columns)

In [10]:
# Gather basic information about the data.
df2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [11]:
# Gather basic information about the data
df2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        157 non-null    object
 1   Region                         157 non-null    object
 2   Happiness Rank                 157 non-null    int64
 3   Happiness Score                157 non-null    float64
 4   Lower Confidence Interval      157 non-null    float64
 5   Upper Confidence Interval      157 non-null    float64
 6   Economy (GDP per Capita)       157 non-null    float64
 7   Family                         157 non-null    float64
 8   Health (Life Expectancy)       157 non-null    float64
 9   Freedom                        157 non-null    float64
 10  Trust (Government Corruption)  157 non-null    float64
 11  Generosity                     157 non-null    float64
 12  Dystopia Residual              157 non-null    float64
dtypes: float64(10), int64(1), object(2)
memory usage: 16.1+ KB

In [12]:
# Gather basic information about data
df2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        155 non-null    object
 1   Happiness.Rank                 155 non-null    int64
 2   Happiness.Score                155 non-null    float64
 3   Whisker.high                   155 non-null    float64
 4   Whisker.low                    155 non-null    float64
 5   Economy..GDP.per.Capita.       155 non-null    float64
 6   Family                         155 non-null    float64
 7   Health..Life.Expectancy.       155 non-null    float64
 8   Freedom                        155 non-null    float64
 9   Generosity                     155 non-null    float64
 10  Trust..Government.Corruption.  155 non-null    float64
 11  Dystopia.Residual              155 non-null    float64
dtypes: float64(10), int64(1), object(1)
memory usage: 14.7+ KB

In [13]:
# Gather basic information about data
df2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     155 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

In [14]:
# Gather basic information about data
df2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

**Gather descriptive statistics about the data.**

In [15]:
# Gather decriptive statistics about data.
df2015.describe()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,79.493671,5.375734,0.047885,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296,2.098977
std,45.754363,1.145010,0.017146,0.403121,0.272369,0.247078,0.150693,0.120034,0.126685,0.553550
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580
25%,40.250000,4.526000,0.037268,0.545808,0.856823,0.439185,0.328330,0.061675,0.150553,1.759410
50%,79.500000,5.232500,0.043940,0.910245,1.029510,0.696705,0.435515,0.107220,0.216130,2.095415
75%,118.750000,6.243750,0.052300,1.158448,1.214405,0.811013,0.549092,0.180255,0.309883,2.462415
max,158.000000,7.587000,0.136930,1.690420,1.402230,1.025250,0.669730,0.551910,0.795880,3.602140

In [16]:
# Gather descriptive statistics about data
df2016.describe()

,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000
mean,78.980892,5.382185,5.282395,5.481975,0.953880,0.793621,0.557619,0.370994,0.137624,0.242635,2.325807
std,45.466030,1.141674,1.148043,1.136493,0.412595,0.266706,0.229349,0.145507,0.111038,0.133756,0.542220
min,1.000000,2.905000,2.732000,3.078000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.817890
25%,40.000000,4.404000,4.327000,4.465000,0.670240,0.641840,0.382910,0.257480,0.061260,0.154570,2.031710
50%,79.000000,5.314000,5.237000,5.419000,1.027800,0.841420,0.596590,0.397470,0.105470,0.222450,2.290740
75%,118.000000,6.269000,6.154000,6.434000,1.279640,1.021520,0.729930,0.484530,0.175540,0.311850,2.664650
max,157.000000,7.526000,7.460000,7.669000,1.824270,1.183260,0.952770,0.608480,0.505210,0.819710,3.837720

In [17]:
# Gather descriptive statistics about data
df2017.describe()

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
count,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000
mean,78.000000,5.354019,5.452326,5.255713,0.984718,1.188898,0.551341,0.408786,0.246883,0.123120,1.850238
std,44.888751,1.131230,1.118542,1.145030,0.420793,0.287263,0.237073,0.149997,0.134780,0.101661,0.500028
min,1.000000,2.693000,2.864884,2.521116,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.377914
25%,39.500000,4.505500,4.608172,4.374955,0.663371,1.042635,0.369866,0.303677,0.154106,0.057271,1.591291
50%,78.000000,5.279000,5.370032,5.193152,1.064578,1.253918,0.606042,0.437454,0.231538,0.089848,1.832910
75%,116.500000,6.101500,6.194600,6.006527,1.318027,1.414316,0.723008,0.516561,0.323762,0.153296,2.144654
max,155.000000,7.537000,7.622030,7.479556,1.870766,1.610574,0.949492,0.658249,0.838075,0.464308,3.117485

In [18]:
# Gather descriptive statistics
df2018.describe()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,155.000000
mean,78.500000,5.375917,0.891449,1.213237,0.597346,0.454506,0.181006,0.112000
std,45.177428,1.119506,0.391921,0.302372,0.247579,0.162424,0.098471,0.096492
min,1.000000,2.905000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.453750,0.616250,1.066750,0.422250,0.356000,0.109500,0.051000
50%,78.500000,5.378000,0.949500,1.255000,0.644000,0.487000,0.174000,0.082000
75%,117.250000,6.168500,1.197750,1.463000,0.777250,0.578500,0.239000,0.137000
max,156.000000,7.632000,2.096000,1.644000,1.030000,0.724000,0.598000,0.457000

In [19]:
# Gather descriptive statistic
df2019.describe()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,78.500000,5.407096,0.905147,1.208814,0.725244,0.392571,0.184846,0.110603
std,45.177428,1.113120,0.398389,0.299191,0.242124,0.143289,0.095254,0.094538
min,1.000000,2.853000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.544500,0.602750,1.055750,0.547750,0.308000,0.108750,0.047000
50%,78.500000,5.379500,0.960000,1.271500,0.789000,0.417000,0.177500,0.085500
75%,117.250000,6.184500,1.232500,1.452500,0.881750,0.507250,0.248250,0.141250
max,156.000000,7.769000,1.684000,1.624000,1.141000,0.631000,0.566000,0.453000

**Removing columns*
* Check column names
* Remove columns
* Rename columns

In [20]:
# Check column names
df2015.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [21]:
# Check column names
df2016.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [22]:
# Check column names
df2017.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='object')

In [23]:
# Check column names
df2018.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [24]:
# Check column names
df2019.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

**Remove columns**

In [25]:
# Remove columns
df2015 = df2015.drop(columns = ['Region', 'Standard Error', 'Dystopia Residual'])

df2015.columns

Index(['Country', 'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity'],
      dtype='object')

In [26]:
# Remove columns from df2016
df2016 = df2016.drop(columns = ['Region', 'Lower Confidence Interval', 'Upper Confidence Interval', 
                                'Dystopia Residual'])

# Display column names
df2016.columns

Index(['Country', 'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity'],
      dtype='object')

In [27]:
# Remove columns from df2017
df2017 = df2017.drop(columns = ['Whisker.high', 'Whisker.low', 'Dystopia.Residual'])

# Display column nammes
df2017.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score',
       'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.',
       'Freedom', 'Generosity', 'Trust..Government.Corruption.'],
      dtype='object')

**Rename columns**
As a data cleaning step rename the columns as needed. Standardize the column names, so that they are all snake_case, correct column names that are misspelt, and make column names more concise as needed.

In [28]:
# Rename columns in df2015

df2015.rename(columns={'Country':'country'}, inplace=True)
df2015.rename(columns={'Happiness Rank':'happiness_rank'}, inplace=True)
df2015.rename(columns={'Happiness Score':'happiness_score'}, inplace=True)
df2015.rename(columns={'Economy (GDP per Capita)':'economy'}, inplace=True)
df2015.rename(columns={'Family':'family'}, inplace=True)
df2015.rename(columns={'Health (Life Expectancy)':'health'}, inplace=True)
df2015.rename(columns={'Freedom':'freedom'}, inplace=True)
df2015.rename(columns={'Trust (Government Corruption)':'trust'}, inplace=True)
df2015.rename(columns={'Generosity':'generosity'}, inplace=True)

# Display updated column names
print(df2015.columns)

Index(['country', 'happiness_rank', 'happiness_score', 'economy', 'family',
       'health', 'freedom', 'trust', 'generosity'],
      dtype='object')

In [29]:
# Rename columns in df2016
df2016.rename(columns={'Country':'country'}, inplace=True)
df2016.rename(columns={'Happiness Rank':'happiness_rank'}, inplace=True)
df2016.rename(columns={'Happiness Score':'happiness_score'}, inplace=True)
df2016.rename(columns={'Economy (GDP per Capita)':'economy'}, inplace=True)
df2016.rename(columns={'Family':'family'}, inplace=True)
df2016.rename(columns={'Health (Life Expectancy)':'health'}, inplace=True)
df2016.rename(columns={'Freedom':'freedom'}, inplace=True)
df2016.rename(columns={'Trust (Government Corruption)':'trust'}, inplace=True)
df2016.rename(columns={'Generosity':'generosity'}, inplace=True)

print(df2016.columns)

Index(['country', 'happiness_rank', 'happiness_score', 'economy', 'family',
       'health', 'freedom', 'trust', 'generosity'],
      dtype='object')

In [30]:
# Rename columns in df2017
df2017.rename(columns={'Country':'country'}, inplace=True)
df2017.rename(columns={'Happiness.Rank':'happiness_rank'}, inplace=True)
df2017.rename(columns={'Happiness.Score':'happiness_score'}, inplace=True)
df2017.rename(columns={'Economy..GDP.per.Capita.':'economy'}, inplace=True)
df2017.rename(columns={'Family':'family'}, inplace=True)
df2017.rename(columns={'Health..Life.Expectancy.':'health'}, inplace=True)
df2017.rename(columns={'Freedom':'freedom'}, inplace=True)
df2017.rename(columns={'Generosity':'generosity'}, inplace=True)
df2017.rename(columns={'Trust..Government.Corruption.':'trust'}, inplace=True)

#Display updated column names
print(df2017.columns)

Index(['country', 'happiness_rank', 'happiness_score', 'economy', 'family',
       'health', 'freedom', 'generosity', 'trust'],
      dtype='object')

In [31]:
# Rename columns in df2018
df2018.rename(columns={'Overall rank':'happiness_rank'}, inplace=True)
df2018.rename(columns={'Country or region':'country'}, inplace=True)
df2018.rename(columns={'Score':'happiness_score'}, inplace=True)
df2018.rename(columns={'GDP per capita':'economy'}, inplace=True)
df2018.rename(columns={'Social support':'family'}, inplace=True)
df2018.rename(columns={'Healthy life expectancy':'health'}, inplace=True)
df2018.rename(columns={'Freedom to make life choices':'freedom'}, inplace=True)
df2018.rename(columns={'Generosity':'generosity'}, inplace=True)
df2018.rename(columns={'Perceptions of corruption':'trust'}, inplace=True)

# Display updated column names
print(df2018.columns)

Index(['happiness_rank', 'country', 'happiness_score', 'economy', 'family',
       'health', 'freedom', 'generosity', 'trust'],
      dtype='object')

In [32]:
print(df2018)

     happiness_rank                   country  happiness_score  economy  \
0                 1                   Finland            7.632    1.305
1                 2                    Norway            7.594    1.456
2                 3                   Denmark            7.555    1.351
3                 4                   Iceland            7.495    1.343
4                 5               Switzerland            7.487    1.420
..              ...                       ...              ...      ...
151             152                     Yemen            3.355    0.442
152             153                  Tanzania            3.303    0.455
153             154               South Sudan            3.254    0.337
154             155  Central African Republic            3.083    0.024
155             156                   Burundi            2.905    0.091

     family  health  freedom  generosity  trust
0     1.592   0.874    0.681       0.202  0.393
1     1.582   0.861    0.686       0.286  0.340
2     1.590   0.868    0.683       0.284  0.408
3     1.644   0.914    0.677       0.353  0.138
4     1.549   0.927    0.660       0.256  0.357
..      ...     ...      ...         ...    ...
151   1.073   0.343    0.244       0.083  0.064
152   0.991   0.381    0.481       0.270  0.097
153   0.608   0.177    0.112       0.224  0.106
154   0.000   0.010    0.305       0.218  0.038
155   0.627   0.145    0.065       0.149  0.076

[156 rows x 9 columns]

In [33]:
df2018.rename(columns={'happiness':'happiness_rank'}, inplace=True)

print(df2018.columns)

Index(['happiness_rank', 'country', 'happiness_score', 'economy', 'family',
       'health', 'freedom', 'generosity', 'trust'],
      dtype='object')

In [34]:
# Rename columns in df2019
df2019.rename(columns={'Overall rank':'happiness_rank'}, inplace=True)
df2019.rename(columns={'Country or region':'country'}, inplace=True)
df2019.rename(columns={'Score':'happiness_score'}, inplace=True)
df2019.rename(columns={'GDP per capita':'economy'}, inplace=True)
df2019.rename(columns={'Social support':'family'}, inplace=True)
df2019.rename(columns={'Healthy life expectancy':'health'}, inplace=True)
df2019.rename(columns={'Freedom to make life choices':'freedom'}, inplace=True)
df2019.rename(columns={'Generosity':'generosity'}, inplace=True)
df2019.rename(columns={'Perceptions of corruption':'trust'}, inplace=True)

# Display updated column names
print(df2019.columns)

Index(['happiness_rank', 'country', 'happiness_score', 'economy', 'family',
       'health', 'freedom', 'generosity', 'trust'],
      dtype='object')

**Rearrange columns**

In [35]:
arrange_columns = ['country', 'happiness_rank', 'happiness_score', 'economy', 'family', 'health',
                 'freedom', 'trust', 'generosity']

In [36]:
# Rearrange column names in df 2017
df2017 = df2017[arrange_columns]

# Verify rearrange column names

print(df2017.columns)

Index(['country', 'happiness_rank', 'happiness_score', 'economy', 'family',
       'health', 'freedom', 'trust', 'generosity'],
      dtype='object')

In [37]:
# Rearrange column names in df2018
df2018 = df2018[arrange_columns]

# verify rearrange column names
print(df2018.columns)

Index(['country', 'happiness_rank', 'happiness_score', 'economy', 'family',
       'health', 'freedom', 'trust', 'generosity'],
      dtype='object')

In [38]:
# Rearrange column names in df2019
df2019 = df2019[arrange_columns]

# Verify rearrange column names
print(df2019.columns)

Index(['country', 'happiness_rank', 'happiness_score', 'economy', 'family',
       'health', 'freedom', 'trust', 'generosity'],
      dtype='object')

**Check missing values**
Check for missing values in the data

In [39]:
# Check for missing values in df2015
df2015.isna().sum()

country            0
happiness_rank     0
happiness_score    0
economy            0
family             0
health             0
freedom            0
trust              0
generosity         0
dtype: int64

In [40]:
# Check for missing values in df2016
df2016.isna().sum()

country            0
happiness_rank     0
happiness_score    0
economy            0
family             0
health             0
freedom            0
trust              0
generosity         0
dtype: int64

In [41]:
# Check for missing values in df2017
df2017.isna().sum()

country            0
happiness_rank     0
happiness_score    0
economy            0
family             0
health             0
freedom            0
trust              0
generosity         0
dtype: int64

In [42]:
# Check for missing values in df2018
df2018.isna().sum()

country            0
happiness_rank     0
happiness_score    0
economy            0
family             0
health             0
freedom            0
trust              1
generosity         0
dtype: int64

In [43]:
# Drop missing value
df2018 = df2018.dropna()

In [44]:
# Verify missing value is removed
df2018.isna().sum()

country            0
happiness_rank     0
happiness_score    0
economy            0
family             0
health             0
freedom            0
trust              0
generosity         0
dtype: int64

In [45]:
# Check for missing values in  df2019
df2019.isna().sum()

country            0
happiness_rank     0
happiness_score    0
economy            0
family             0
health             0
freedom            0
trust              0
generosity         0
dtype: int64

**Check for duplicates**

Check for duplicated values in the data

In [46]:
# Check for duplicates
df2015.duplicated().sum()

0

**There are no duplicates in df2015**

In [47]:
# Check for duplicates in df2016
df2016.duplicated().sum()

0

**There are no duplicates in df2016**

In [48]:
# Check for duplicates in df2017
df2017.duplicated().sum()

0

**There are no duplicates in df2017**

In [49]:
# Check for duplicates in df2018
df2018.duplicated().sum()

0

**There are no duplicates in df2018**

In [50]:
# Check for duplicates in df2019
df2019.duplicated().sum()

0

**There are no duplicates in df2019**

In [51]:
# Add year column to each dataframe
df2015['year'] = 2015
df2016['year'] = 2016
df2017['year'] = 2017
df2018['year'] = 2018
df2019['year'] = 2019

In [52]:
df2015.head()

,country,happiness_rank,happiness_score,economy,family,health,freedom,trust,generosity,year
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2015
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015

**Merging Data Frames**

In [53]:
# Merge dataframes df2015, df2016, df2017, df2018, df2019
df_merge = pd.concat([df2015, df2016, df2017, df2018, df2019], ignore_index=True)

In [54]:
# Verify the dataset is merged
df_merge

,country,happiness_rank,happiness_score,economy,family,health,freedom,trust,generosity,year
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2015
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015
...,...,...,...,...,...,...,...,...,...,...
776,Rwanda,152,3.334,0.35900,0.71100,0.61400,0.55500,0.41100,0.21700,2019
777,Tanzania,153,3.231,0.47600,0.88500,0.49900,0.41700,0.14700,0.27600,2019
778,Afghanistan,154,3.203,0.35000,0.51700,0.36100,0.00000,0.02500,0.15800,2019
779,Central African Republic,155,3.083,0.02600,0.00000,0.10500,0.22500,0.03500,0.23500,2019
780,South Sudan,156,2.853,0.30600,0.57500,0.29500,0.01000,0.09100,0.20200,2019

In [55]:
# Save dataset 
df_merge.to_csv('df_merge.csv', index=False)